openapi: 3.0.1
info:
  title: Python Executor Plugin
  description: A plugin that allows the user to run Python code in their local environment.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /run_python_code:
    post:
      operationId: runPythonCode
      summary: Run Python code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runPythonCodeRequest'
      responses:
        "200":
          description: OK

  /run_python_ast_code:
    post:
      operationId: runPythonAstCode
      summary: Run Python code with AST
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/runPythonAstCodeRequest'
      responses:
        "200":
          description: OK

components:
  schemas:
    runPythonCodeRequest:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          description: The Python code to run.

    runPythonAstCodeRequest:
      type: object
      required:
      - code
      properties:
        code:
          type: string
          description: The Python code to run with AST.